{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.cmaterialcolors",
    "module": "release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "release-1.0.0.aar",
          "url": "release-1.0.0.aar",
          "size": 22009,
          "sha512": "975618eafb15a8178bfa7dcec922635cd41c389b77a107756c00350d3657a3a3f59db41159be3544b8a31e8a7f565139abdab2b391a40aa19e7f772c90fc98a7",
          "sha256": "cf8f5d17f98a85a9edf6f7ecbb53222015ef113ad93d7c7878a98174a73ad657",
          "sha1": "f69c15d07890a72b1fa339ddb7d1a28e4fcfc332",
          "md5": "493fd7931f86b0816a1bd41afeea7776"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta08"
          }
        }
      ],
      "files": [
        {
          "name": "release-1.0.0.aar",
          "url": "release-1.0.0.aar",
          "size": 22009,
          "sha512": "975618eafb15a8178bfa7dcec922635cd41c389b77a107756c00350d3657a3a3f59db41159be3544b8a31e8a7f565139abdab2b391a40aa19e7f772c90fc98a7",
          "sha256": "cf8f5d17f98a85a9edf6f7ecbb53222015ef113ad93d7c7878a98174a73ad657",
          "sha1": "f69c15d07890a72b1fa339ddb7d1a28e4fcfc332",
          "md5": "493fd7931f86b0816a1bd41afeea7776"
        }
      ]
    }
  ]
}
