{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.composelib",
    "module": "cmaterialcolors",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "cmaterialcolors-1.0.2.aar",
          "url": "cmaterialcolors-1.0.2.aar",
          "size": 22101,
          "sha512": "a7a3f740a944bb9ec7d0d0c19de45ef9327a617d668f85aee0f87ec18554fef20cae29e58cc0bb91cb216b681cd136d73b59948f3d5a3c2d605c892157200f2a",
          "sha256": "4302142837d89e3bff812907b085d5c26307debb59fcf140a778d2516cab2834",
          "sha1": "76f5245e5eed311500e68c08d8e0e130acf63c66",
          "md5": "fc729c5c5287733ffc2d66621bfd6a87"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "cmaterialcolors-1.0.2.aar",
          "url": "cmaterialcolors-1.0.2.aar",
          "size": 22101,
          "sha512": "a7a3f740a944bb9ec7d0d0c19de45ef9327a617d668f85aee0f87ec18554fef20cae29e58cc0bb91cb216b681cd136d73b59948f3d5a3c2d605c892157200f2a",
          "sha256": "4302142837d89e3bff812907b085d5c26307debb59fcf140a778d2516cab2834",
          "sha1": "76f5245e5eed311500e68c08d8e0e130acf63c66",
          "md5": "fc729c5c5287733ffc2d66621bfd6a87"
        }
      ]
    }
  ]
}
